# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 16:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment_todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField(blank=True)),
                ('pinned', models.BooleanField(default=False)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private', models.BooleanField(default=False)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjmanUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='uploads/photos/%Y/%m/%d')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='To_do',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('details', models.TextField(blank=True)),
                ('done', models.BooleanField(default=False)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projman.ProjmanUser')),
                ('parent_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projman.Project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projman.ProjmanUser'),
        ),
        migrations.AddField(
            model_name='participation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projman.Project'),
        ),
        migrations.AddField(
            model_name='participation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projman.ProjmanUser'),
        ),
        migrations.AddField(
            model_name='note',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projman.ProjmanUser'),
        ),
        migrations.AddField(
            model_name='note',
            name='parent_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projman.Project'),
        ),
        migrations.AddField(
            model_name='designation',
            name='todo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projman.To_do'),
        ),
        migrations.AddField(
            model_name='designation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projman.ProjmanUser'),
        ),
        migrations.AddField(
            model_name='comment_todo',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projman.ProjmanUser'),
        ),
        migrations.AddField(
            model_name='comment_todo',
            name='parent_todo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projman.To_do'),
        ),
        migrations.AddField(
            model_name='comment_note',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projman.ProjmanUser'),
        ),
        migrations.AddField(
            model_name='comment_note',
            name='parent_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projman.Note'),
        ),
    ]
