# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projman', '0004_auto_20160226_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projman.Project')),
            ],
        ),
    ]
